/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'acer-pc' at '18-6-11 下午7:27' with Gradle 3.2.1
 *
 * @author acer-pc, @date 18-6-11 下午7:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
